
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5093:5093"
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development