
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - NODE_ENV=development